mise.res[mise.res$scenario=="sp.1.v1",]
mise.res[mise.res$scenario=="sp.1.v2",]
mise.res[mise.res$scenario=="sp.1.v3",]
mise.res[mise.res$scenario=="sp.1.v4",]
mise.res[mise.res$scenario=="sp.1.v5",]
mise.res[mise.res$scenario=="sp.3.v1",]
mise.res[mise.res$scenario=="sp.3.v2",]
mise.res[mise.res$scenario=="sp.3.v3",]
mise.res[mise.res$scenario=="sp.3.v4",]
mise.res[mise.res$scenario=="sp.3.v5",]

mise.res[mise.res$scenario=="bump.1.v1",]
mise.res[mise.res$scenario=="bump.1.v2",]
mise.res[mise.res$scenario=="bump.1.v3",]
mise.res[mise.res$scenario=="bump.1.v4",]
mise.res[mise.res$scenario=="bump.1.v5",]
mise.res[mise.res$scenario=="bump.3.v1",]
mise.res[mise.res$scenario=="bump.3.v2",]
mise.res[mise.res$scenario=="bump.3.v3",]
mise.res[mise.res$scenario=="bump.3.v4",]
mise.res[mise.res$scenario=="bump.3.v5",]

mise.res[mise.res$scenario=="blk.1.v1",]
mise.res[mise.res$scenario=="blk.1.v2",]
mise.res[mise.res$scenario=="blk.1.v3",]
mise.res[mise.res$scenario=="blk.1.v4",]
mise.res[mise.res$scenario=="blk.1.v5",]
mise.res[mise.res$scenario=="blk.3.v1",]
mise.res[mise.res$scenario=="blk.3.v2",]
mise.res[mise.res$scenario=="blk.3.v3",]
mise.res[mise.res$scenario=="blk.3.v4",]
mise.res[mise.res$scenario=="blk.3.v5",]

mise.res[mise.res$scenario=="ang.1.v1",]
mise.res[mise.res$scenario=="ang.1.v2",]
mise.res[mise.res$scenario=="ang.1.v3",]
mise.res[mise.res$scenario=="ang.1.v4",]
mise.res[mise.res$scenario=="ang.1.v5",]
mise.res[mise.res$scenario=="ang.3.v1",]
mise.res[mise.res$scenario=="ang.3.v2",]
mise.res[mise.res$scenario=="ang.3.v3",]
mise.res[mise.res$scenario=="ang.3.v4",]
mise.res[mise.res$scenario=="ang.3.v5",]

mise.res[mise.res$scenario=="dop.1.v1",]
mise.res[mise.res$scenario=="dop.1.v2",]
mise.res[mise.res$scenario=="dop.1.v3",]
mise.res[mise.res$scenario=="dop.1.v4",]
mise.res[mise.res$scenario=="dop.1.v5",]
mise.res[mise.res$scenario=="dop.3.v1",]
mise.res[mise.res$scenario=="dop.3.v2",]
mise.res[mise.res$scenario=="dop.3.v3",]
mise.res[mise.res$scenario=="dop.3.v4",]
mise.res[mise.res$scenario=="dop.3.v5",]

mise.res[mise.res$scenario=="blip.1.v1",]
mise.res[mise.res$scenario=="blip.1.v2",]
mise.res[mise.res$scenario=="blip.1.v3",]
mise.res[mise.res$scenario=="blip.1.v4",]
mise.res[mise.res$scenario=="blip.1.v5",]
mise.res[mise.res$scenario=="blip.3.v1",]
mise.res[mise.res$scenario=="blip.3.v2",]
mise.res[mise.res$scenario=="blip.3.v3",]
mise.res[mise.res$scenario=="blip.3.v4",]
mise.res[mise.res$scenario=="blip.3.v5",]

mise.res[mise.res$scenario=="cor.1.v1",]
mise.res[mise.res$scenario=="cor.1.v2",]
mise.res[mise.res$scenario=="cor.1.v3",]
mise.res[mise.res$scenario=="cor.1.v4",]
mise.res[mise.res$scenario=="cor.1.v5",]
mise.res[mise.res$scenario=="cor.3.v1",]
mise.res[mise.res$scenario=="cor.3.v2",]
mise.res[mise.res$scenario=="cor.3.v3",]
mise.res[mise.res$scenario=="cor.3.v4",]
mise.res[mise.res$scenario=="cor.3.v5",]


