sourceDir("methods")
methods=list()

methods[[1]] = list(name="ebayesthresh",fn=ebayesthresh.wrapper,args=list())
methods[[2]] = list(name="smash.homo.haar",fn=smash.homo.wrapper,args=list(filter.number=1,family="DaubExPhase"))
methods[[3]] = list(name="smash.homo.s8",fn=smash.homo.wrapper,args=list(filter.number=8,family="DaubLeAsymm"))
methods[[4]] = list(name="smash.haar",fn=smash.wrapper,args=list(filter.number=1,family="DaubExPhase"))
methods[[5]] = list(name="smash.s8",fn=smash.wrapper,args=list(filter.number=8,family="DaubLeAsymm"))
methods[[6]] = list(name="smash.jash",fn=smash.jash.wrapper,args=list(filter.number=8,family="DaubLeAsymm"))
methods[[7]] = list(name="tithresh.rmad.haar",fn=tithresh.wrapper,args=list(method="rmad",filter.number=1,family="DaubExPhase"))
methods[[8]] = list(name="tithresh.rmad.s8",fn=tithresh.wrapper,args=list(method="rmad",filter.number=8,family="DaubLeAsymm"))
methods[[9]] = list(name="tithresh.smash.haar",fn=tithresh.wrapper,args=list(method="smash",filter.number=1,family="DaubExPhase"))
methods[[10]] = list(name="tithresh.smash.s8",fn=tithresh.wrapper,args=list(method="smash",filter.number=8,family="DaubLeAsymm"))
methods[[11]] = list(name="smash.true.haar",fn=smash.true.wrapper,args=list(filter.number=1,family="DaubExPhase"))
methods[[12]] = list(name="smash.true.s8",fn=smash.true.wrapper,args=list(filter.number=8,family="DaubLeAsymm"))
methods[[13]] = list(name="tithresh.true.haar",fn=tithresh.true.wrapper,args=list(filter.number=1,family="DaubExPhase"))
methods[[14]] = list(name="tithresh.true.s8",fn=tithresh.true.wrapper,args=list(filter.number=8,family="DaubLeAsymm"))
