sourceDir("datamakers")


scenarios=list()
scenarios[[1]]=list(name="sp.1.v1",fn=datamaker,args=list(n=1024,meanfn="spikes",varfn=1,rsnr=sqrt(1)),seed=1)
scenarios[[2]]=list(name="sp.1.v2",fn=datamaker,args=list(n=1024,meanfn="spikes",varfn=2,rsnr=sqrt(1)),seed=1)
scenarios[[3]]=list(name="sp.1.v3",fn=datamaker,args=list(n=1024,meanfn="spikes",varfn=3,rsnr=sqrt(1)),seed=1)
scenarios[[4]]=list(name="sp.1.v4",fn=datamaker,args=list(n=1024,meanfn="spikes",varfn=4,rsnr=sqrt(1)),seed=1)
scenarios[[5]]=list(name="sp.1.v5",fn=datamaker,args=list(n=1024,meanfn="spikes",varfn=5,rsnr=sqrt(1)),seed=1)
scenarios[[6]]=list(name="sp.3.v1",fn=datamaker,args=list(n=1024,meanfn="spikes",varfn=1,rsnr=sqrt(3)),seed=1)
scenarios[[7]]=list(name="sp.3.v2",fn=datamaker,args=list(n=1024,meanfn="spikes",varfn=2,rsnr=sqrt(3)),seed=1)
scenarios[[8]]=list(name="sp.3.v3",fn=datamaker,args=list(n=1024,meanfn="spikes",varfn=3,rsnr=sqrt(3)),seed=1)
scenarios[[9]]=list(name="sp.3.v4",fn=datamaker,args=list(n=1024,meanfn="spikes",varfn=4,rsnr=sqrt(3)),seed=1)
scenarios[[10]]=list(name="sp.3.v5",fn=datamaker,args=list(n=1024,meanfn="spikes",varfn=5,rsnr=sqrt(3)),seed=1)

scenarios[[11]]=list(name="bump.1.v1",fn=datamaker,args=list(n=1024,meanfn="bumps",varfn=1,rsnr=sqrt(1)),seed=1)
scenarios[[12]]=list(name="bump.1.v2",fn=datamaker,args=list(n=1024,meanfn="bumps",varfn=2,rsnr=sqrt(1)),seed=1)
scenarios[[13]]=list(name="bump.1.v3",fn=datamaker,args=list(n=1024,meanfn="bumps",varfn=3,rsnr=sqrt(1)),seed=1)
scenarios[[14]]=list(name="bump.1.v4",fn=datamaker,args=list(n=1024,meanfn="bumps",varfn=4,rsnr=sqrt(1)),seed=1)
scenarios[[15]]=list(name="bump.1.v5",fn=datamaker,args=list(n=1024,meanfn="bumps",varfn=5,rsnr=sqrt(1)),seed=1)
scenarios[[16]]=list(name="bump.3.v1",fn=datamaker,args=list(n=1024,meanfn="bumps",varfn=1,rsnr=sqrt(3)),seed=1)
scenarios[[17]]=list(name="bump.3.v2",fn=datamaker,args=list(n=1024,meanfn="bumps",varfn=2,rsnr=sqrt(3)),seed=1)
scenarios[[18]]=list(name="bump.3.v3",fn=datamaker,args=list(n=1024,meanfn="bumps",varfn=3,rsnr=sqrt(3)),seed=1)
scenarios[[19]]=list(name="bump.3.v4",fn=datamaker,args=list(n=1024,meanfn="bumps",varfn=4,rsnr=sqrt(3)),seed=1)
scenarios[[20]]=list(name="bump.3.v5",fn=datamaker,args=list(n=1024,meanfn="bumps",varfn=5,rsnr=sqrt(3)),seed=1)

scenarios[[21]]=list(name="blk.1.v1",fn=datamaker,args=list(n=1024,meanfn="blocks",varfn=1,rsnr=sqrt(1)),seed=1)
scenarios[[22]]=list(name="blk.1.v2",fn=datamaker,args=list(n=1024,meanfn="blocks",varfn=2,rsnr=sqrt(1)),seed=1)
scenarios[[23]]=list(name="blk.1.v3",fn=datamaker,args=list(n=1024,meanfn="blocks",varfn=3,rsnr=sqrt(1)),seed=1)
scenarios[[24]]=list(name="blk.1.v4",fn=datamaker,args=list(n=1024,meanfn="blocks",varfn=4,rsnr=sqrt(1)),seed=1)
scenarios[[25]]=list(name="blk.1.v5",fn=datamaker,args=list(n=1024,meanfn="blocks",varfn=5,rsnr=sqrt(1)),seed=1)
scenarios[[26]]=list(name="blk.3.v1",fn=datamaker,args=list(n=1024,meanfn="blocks",varfn=1,rsnr=sqrt(3)),seed=1)
scenarios[[27]]=list(name="blk.3.v2",fn=datamaker,args=list(n=1024,meanfn="blocks",varfn=2,rsnr=sqrt(3)),seed=1)
scenarios[[28]]=list(name="blk.3.v3",fn=datamaker,args=list(n=1024,meanfn="blocks",varfn=3,rsnr=sqrt(3)),seed=1)
scenarios[[29]]=list(name="blk.3.v4",fn=datamaker,args=list(n=1024,meanfn="blocks",varfn=4,rsnr=sqrt(3)),seed=1)
scenarios[[30]]=list(name="blk.3.v5",fn=datamaker,args=list(n=1024,meanfn="blocks",varfn=5,rsnr=sqrt(3)),seed=1)

scenarios[[31]]=list(name="ang.1.v1",fn=datamaker,args=list(n=1024,meanfn="angles",varfn=1,rsnr=sqrt(1)),seed=1)
scenarios[[32]]=list(name="ang.1.v2",fn=datamaker,args=list(n=1024,meanfn="angles",varfn=2,rsnr=sqrt(1)),seed=1)
scenarios[[33]]=list(name="ang.1.v3",fn=datamaker,args=list(n=1024,meanfn="angles",varfn=3,rsnr=sqrt(1)),seed=1)
scenarios[[34]]=list(name="ang.1.v4",fn=datamaker,args=list(n=1024,meanfn="angles",varfn=4,rsnr=sqrt(1)),seed=1)
scenarios[[35]]=list(name="ang.1.v5",fn=datamaker,args=list(n=1024,meanfn="angles",varfn=5,rsnr=sqrt(1)),seed=1)
scenarios[[36]]=list(name="ang.3.v1",fn=datamaker,args=list(n=1024,meanfn="angles",varfn=1,rsnr=sqrt(3)),seed=1)
scenarios[[37]]=list(name="ang.3.v2",fn=datamaker,args=list(n=1024,meanfn="angles",varfn=2,rsnr=sqrt(3)),seed=1)
scenarios[[38]]=list(name="ang.3.v3",fn=datamaker,args=list(n=1024,meanfn="angles",varfn=3,rsnr=sqrt(3)),seed=1)
scenarios[[39]]=list(name="ang.3.v4",fn=datamaker,args=list(n=1024,meanfn="angles",varfn=4,rsnr=sqrt(3)),seed=1)
scenarios[[40]]=list(name="ang.3.v5",fn=datamaker,args=list(n=1024,meanfn="angles",varfn=5,rsnr=sqrt(3)),seed=1)

scenarios[[41]]=list(name="dop.1.v1",fn=datamaker,args=list(n=1024,meanfn="doppler",varfn=1,rsnr=sqrt(1)),seed=1)
scenarios[[42]]=list(name="dop.1.v2",fn=datamaker,args=list(n=1024,meanfn="doppler",varfn=2,rsnr=sqrt(1)),seed=1)
scenarios[[43]]=list(name="dop.1.v3",fn=datamaker,args=list(n=1024,meanfn="doppler",varfn=3,rsnr=sqrt(1)),seed=1)
scenarios[[44]]=list(name="dop.1.v4",fn=datamaker,args=list(n=1024,meanfn="doppler",varfn=4,rsnr=sqrt(1)),seed=1)
scenarios[[45]]=list(name="dop.1.v5",fn=datamaker,args=list(n=1024,meanfn="doppler",varfn=5,rsnr=sqrt(1)),seed=1)
scenarios[[46]]=list(name="dop.3.v1",fn=datamaker,args=list(n=1024,meanfn="doppler",varfn=1,rsnr=sqrt(3)),seed=1)
scenarios[[47]]=list(name="dop.3.v2",fn=datamaker,args=list(n=1024,meanfn="doppler",varfn=2,rsnr=sqrt(3)),seed=1)
scenarios[[48]]=list(name="dop.3.v3",fn=datamaker,args=list(n=1024,meanfn="doppler",varfn=3,rsnr=sqrt(3)),seed=1)
scenarios[[49]]=list(name="dop.3.v4",fn=datamaker,args=list(n=1024,meanfn="doppler",varfn=4,rsnr=sqrt(3)),seed=1)
scenarios[[50]]=list(name="dop.3.v5",fn=datamaker,args=list(n=1024,meanfn="doppler",varfn=5,rsnr=sqrt(3)),seed=1)

scenarios[[51]]=list(name="blip.1.v1",fn=datamaker,args=list(n=1024,meanfn="blip",varfn=1,rsnr=sqrt(1)),seed=1)
scenarios[[52]]=list(name="blip.1.v2",fn=datamaker,args=list(n=1024,meanfn="blip",varfn=2,rsnr=sqrt(1)),seed=1)
scenarios[[53]]=list(name="blip.1.v3",fn=datamaker,args=list(n=1024,meanfn="blip",varfn=3,rsnr=sqrt(1)),seed=1)
scenarios[[54]]=list(name="blip.1.v4",fn=datamaker,args=list(n=1024,meanfn="blip",varfn=4,rsnr=sqrt(1)),seed=1)
scenarios[[55]]=list(name="blip.1.v5",fn=datamaker,args=list(n=1024,meanfn="blip",varfn=5,rsnr=sqrt(1)),seed=1)
scenarios[[56]]=list(name="blip.3.v1",fn=datamaker,args=list(n=1024,meanfn="blip",varfn=1,rsnr=sqrt(3)),seed=1)
scenarios[[57]]=list(name="blip.3.v2",fn=datamaker,args=list(n=1024,meanfn="blip",varfn=2,rsnr=sqrt(3)),seed=1)
scenarios[[58]]=list(name="blip.3.v3",fn=datamaker,args=list(n=1024,meanfn="blip",varfn=3,rsnr=sqrt(3)),seed=1)
scenarios[[59]]=list(name="blip.3.v4",fn=datamaker,args=list(n=1024,meanfn="blip",varfn=4,rsnr=sqrt(3)),seed=1)
scenarios[[60]]=list(name="blip.3.v5",fn=datamaker,args=list(n=1024,meanfn="blip",varfn=5,rsnr=sqrt(3)),seed=1)

scenarios[[61]]=list(name="cor.1.v1",fn=datamaker,args=list(n=1024,meanfn="corner",varfn=1,rsnr=sqrt(1)),seed=1)
scenarios[[62]]=list(name="cor.1.v2",fn=datamaker,args=list(n=1024,meanfn="corner",varfn=2,rsnr=sqrt(1)),seed=1)
scenarios[[63]]=list(name="cor.1.v3",fn=datamaker,args=list(n=1024,meanfn="corner",varfn=3,rsnr=sqrt(1)),seed=1)
scenarios[[64]]=list(name="cor.1.v4",fn=datamaker,args=list(n=1024,meanfn="corner",varfn=4,rsnr=sqrt(1)),seed=1)
scenarios[[65]]=list(name="cor.1.v5",fn=datamaker,args=list(n=1024,meanfn="corner",varfn=5,rsnr=sqrt(1)),seed=1)
scenarios[[66]]=list(name="cor.3.v1",fn=datamaker,args=list(n=1024,meanfn="corner",varfn=1,rsnr=sqrt(3)),seed=1)
scenarios[[67]]=list(name="cor.3.v2",fn=datamaker,args=list(n=1024,meanfn="corner",varfn=2,rsnr=sqrt(3)),seed=1)
scenarios[[68]]=list(name="cor.3.v3",fn=datamaker,args=list(n=1024,meanfn="corner",varfn=3,rsnr=sqrt(3)),seed=1)
scenarios[[69]]=list(name="cor.3.v4",fn=datamaker,args=list(n=1024,meanfn="corner",varfn=4,rsnr=sqrt(3)),seed=1)
scenarios[[70]]=list(name="cor.3.v5",fn=datamaker,args=list(n=1024,meanfn="corner",varfn=5,rsnr=sqrt(3)),seed=1)
